apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  name: sample-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: sample-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
